branches:
  - "master"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }]
  - [
      "@semantic-release/exec",
      {
        prepareCmd: "npm version ${nextRelease.version} --git-tag-version false",
      },
    ]
  - ["@semantic-release/exec", { prepareCmd: "npm publish --access public" }]
  - [ '@semantic-release/npm']
  - [
      "@semantic-release/git",
      {
        assets:
          [
            "package.json",
            "package-lock.json",
            "CHANGELOG.md",
            "docs/**/*"
          ],
        message: "chore(release): release ${nextRelease.version}
          ${nextRelease.notes}",
      },
    ]
 
