branches:
  - name: '@pluto-encrypted/database/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/test-suite/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/shared/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/leveldb/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/inmemory/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/indexdb/v+([0-9])?(.*([0-9])|X).X'

  - name: '@pluto-encrypted/encryption/v+([0-9])?(.*([0-9])|X).X'

  - name: 'master'
  - name: 'release/*'
    prerelease: 'rc'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }]
  - [
      "@semantic-release/exec",
      {
        prepareCmd: "npm version ${nextRelease.version} --git-tag-version false"
      }
    ]
  - ["@semantic-release/exec", { prepareCmd: "npm run build" }]
  - ["@semantic-release/exec", { prepareCmd: "npm publish --access public" }]
  - [
      "@semantic-release/git",
      {
        assets:
          [
            "package.json",
            "package-lock.json",
            "packages/*/CHANGELOG.md",
            "packages/*/package.json",
            "packages/*/package-lock.json",
            "packages/*/README.md"
          ],
        message: "chore(release): release ${nextRelease.version}
          ${nextRelease.notes} [skip ci]"
      },
    ]
  - "@semantic-release/github"

