
name: Continuous integration

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-pluto
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true' 
          token: ${{ secrets.PLUTO_GITHUB }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: CI TASK     
        env:
          GH_TOKEN: ${{ secrets.PLUTO_GITHUB }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
        run: |
          npm ci
          chmod +x coverage.sh
          ./coverage.sh
          npm run coverage

      - name: Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.23
        with:
          coverage-summary-path: packages/database/coverage/coverage-summary.json
