name: Release Maintenance & Release candidate

on:
  push:
    branches:
      - +([0-9])?(.{+([0-9]),x}).x
      - release/*
  workflow_call:
  workflow_dispatch:
        
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'true' 
          token: ${{ secrets.PLUTO_GITHUB }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: 'https://registry.npmjs.org/'
    
      - uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.PLUTO_GITHUB }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "${{ secrets.GIT_AUTHOR_NAME }}"
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GITHUB_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GITHUB_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GITHUB_COMMITER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GITHUB_COMMITER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          CI: true
        run: |
          npm install
          npm run build
          npm run release